### ISSUE TITLE
Logging version information of Git-retrieved software

### ISSUE THREAD

**Issue by ajnelson-nist** [BitCurator/bitcurator-distro-bootstrap#2]
[This line in the bootstrap script](https://github.com/BitCurator/bitcurator-bootstrap/blob/c5207f1a5183db72c23ab816fa6294c84afce4be/bc-bootstrap.sh#L965) initializes downloading and installing Bulk Extractor.  It retrieves whatever is the most current version at installation time.  The [cleanup step](https://github.com/BitCurator/bitcurator-bootstrap/blob/c5207f1a5183db72c23ab816fa6294c84afce4be/bc-bootstrap.sh#L980) then removes the downloaded build files.

The way that `git clone` is run, the version information (particularly, the Git commit) used to build Bulk Extractor is not logged by the bootstrap script.  This is very likely to be useful software provenance information to track.  Bulk Extractor [tracks it](https://github.com/simsong/bulk_extractor/blob/0328eb4af965d019d74a6bc38a9e00271487fdef/configure.ac#L597) in the installed `config.h` file, using an autoconf macro, and one or two of the other packages did as well, but many don't presently (`dumpfloppy`, `sleuthkit`, `hashdeep`, `disktype`).

To assist with future debugging efforts, it may be helpful to add something like this code line to the bootstrap script, immediately after each `cd /tmp/...`:

```
echo "The Git HEAD is `git rev-parse HEAD`." >> $HOME/bitcurator-install.log 2>&1
```

**Comment by kamwoods** [comment]
Fixed in the current salt build at https://github.com/bitcurator/bitcurator-distro-salt.
